spring.application.name=geks

# Webgunea http://localhost:8080 portuan entzungo duela zehazten da.
server.port=8080
# MySQL Konfigurazioa
spring.datasource.url=jdbc:mysql://localhost:3306/maltunaGailuElektronikoakdb?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# Hibernate: Java aplikazioaren eta MySQL datu-basearen arteko itzultzailea da.
# Java objektuak eta datu-baseko taulak lotzen ditu, SQL kode konpletxia idatzi beharrik izan gabe.
# Mapeo antzeko bat egiten du objektua eta taularen artean. Aukera ezberdinak daude:

# Taula ez badago, sortu egiten du.
# spring.jpa.hibernate.ddl-auto=update

# Ez du ezer aldatzen. Java klasea eta MySQL taula berdinak diren begiratzen du. Desberdinak
# badira, errorea ematen du.
spring.jpa.hibernate.ddl-auto=validate

# Aplikazioa piztean taula ezabatu eta berriro sortzen du.
# spring.jpa.hibernate.ddl-auto=create-drop

# Kontsolan Hibernatek exekutatzen dituen SQL aginduak ikusteko.
spring.jpa.show-sql=true
# Hibernatek SQL-ak sortzen dituenean, MySQLra egokitzeko balio du.
# datu base ezberdinak daz, oracle, maria, mysql .... guk azken hau erabiliko dou
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect